# Generated by Django 4.0.6 on 2022-11-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('clan', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('whatsapp', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nickname'],
            },
        ),
    ]
