# Generated by Django 4.0.6 on 2022-11-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
