# Generated by Django 4.0.6 on 2022-11-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externTourneament', '0002_registeredplayers_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredplayers',
            name='clan',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='registeredplayers',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='registeredplayers',
            name='wantInfo',
            field=models.BooleanField(default=False),
        ),
    ]
