# Generated by Django 4.0.6 on 2022-11-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externTourneament', '0003_registeredplayers_clan_registeredplayers_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredplayers',
            name='whatsAppGroup',
            field=models.BooleanField(default=False),
        ),
    ]
