# Generated by Django 4.0.6 on 2022-11-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('externTourneament', '0004_registeredplayers_whatsappgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredplayers',
            name='whatsAppGroup',
        ),
    ]
