# Generated by Django 4.0.6 on 2022-08-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClanMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cargo', models.IntegerField(default=0)),
                ('media', models.FloatField(default=0.0)),
                ('creation_time', models.TimeField()),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clan_memberships', to='clashdata.clan')),
            ],
        ),
    ]
