# Generated by Django 4.0.6 on 2022-08-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clashdata', '0002_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
