# Generated by Django 4.0.6 on 2022-08-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clashdata', '0003_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanmember',
            name='contato',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
