# Generated by Django 4.0.6 on 2022-08-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clashdata', '0004_clanmember_contato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clanmember',
            options={'ordering': ['clan', 'name']},
        ),
        migrations.AlterField(
            model_name='clanmember',
            name='contato',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clanmember',
            name='creation_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
