# Generated by Django 4.0.6 on 2022-08-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clashdata', '0005_alter_clanmember_options_alter_clanmember_contato_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clanmember',
            options={'ordering': ['clan', '-media']},
        ),
        migrations.AlterField(
            model_name='clanmember',
            name='creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
