# Generated by Django 4.0.6 on 2022-08-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clashdata', '0006_alter_clanmember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanMemberHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('clanDestiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_clan_destiny', to='clashdata.clan')),
                ('clanMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_histories', to='clashdata.clanmember')),
                ('clanSource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_clan_source', to='clashdata.clan')),
            ],
        ),
    ]
