# Generated by Django 4.0.6 on 2022-08-21 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clashdata', '0007_clanmemberhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanmemberhistory',
            name='clanDestiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_clan_destiny', to='clashdata.clan'),
        ),
        migrations.AlterField(
            model_name='clanmemberhistory',
            name='clanMember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_histories', to='clashdata.clanmember'),
        ),
        migrations.AlterField(
            model_name='clanmemberhistory',
            name='clanSource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_clan_source', to='clashdata.clan'),
        ),
    ]
