# Generated by Django 4.0.6 on 2022-08-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clashdata', '0010_alter_clanmemberhistory_clansource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanmemberhistory',
            name='clanDestiny',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_clan_destiny', to='clashdata.clan'),
        ),
    ]
