# Generated by Django 4.0.6 on 2022-08-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clashdata', '0012_royaleapiconfig_alter_clanmemberhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='tag',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
