# Generated by Django 4.0.6 on 2022-08-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clashdata', '0013_clan_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoyaleApiConfig',
            new_name='Config',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='ip',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='key',
            new_name='value',
        ),
    ]
