# Generated by Django 4.0.6 on 2022-08-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clashdata', '0014_rename_royaleapiconfig_config_rename_ip_config_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clanmemberhistory',
            name='clanMember',
        ),
        migrations.RemoveField(
            model_name='clanmemberhistory',
            name='operation',
        ),
        migrations.AddField(
            model_name='clanmemberhistory',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clanmemberhistory',
            name='tag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clanmemberhistory',
            name='clanDestiny',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='clanmemberhistory',
            name='clanSource',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
