# Generated by Django 4.0.6 on 2022-10-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clashdata', '0015_remove_clanmemberhistory_clanmember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
