# Generated by Django 4.0.6 on 2023-01-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clashdata', '0016_rival'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanBR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='war_clan', to='clashdata.clan')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=255)),
                ('decksUsed', models.IntegerField(default=0)),
                ('decksUsedToday', models.IntegerField(default=0)),
                ('decksTraining', models.IntegerField(default=0)),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainingday_war', to='clashdata.war')),
            ],
        ),
    ]
